{
 "title": "Home Battery Main",
 "description": "JK Battery Pack",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "wbattery", "label": "Battery", "query": "basengreen, jk" }
  ]
 },
 "panels": [
  {
   "title": "Grid Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Usage-current",
     "query": "SELECT last(\"value\") FROM \"P1Actual\" WHERE (\"idx\"::tag = '1768')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "idx::tag", "operator": "=", "value": "1768" }
     ]
    }
   ]
  },
  {
   "title": "ESS Setpoint",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"domoticz_home\")\r\n  |> range(start: 0)\r\n  |> filter(fn:(r) => r._measurement == \"Setpoint\" and r.idx == \"9448\")\r\n  |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar Production",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"domoticz_home\")\r\n  |> range(start: today())\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"Usage\"\r\n    and r.idx == \"8023\"\r\n  )\r\n  |> aggregateWindow(every: 1d, fn: spread, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000.0}))\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Actual Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Usage",
     "query": "from(bucket:\"domoticz_home\")\r\n  |> range(start: 0)\r\n  |> filter(fn:(r) => r._measurement == \"Usage\" and r.idx == \"8129\")\r\n  |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "idx::tag", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Actual Delivery",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Usage",
     "query": "from(bucket:\"domoticz_home\")\r\n  |> range(start: 0)\r\n  |> filter(fn:(r) => r._measurement == \"Usage\" and r.idx == \"8130\")\r\n  |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "idx::tag", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Schuur Temp",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idx::tag", "operator": "=", "value": "9572" }
     ]
    }
   ]
  },
  {
   "title": "Schuur Hum",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idx::tag", "operator": "=", "value": "9572" }
     ]
    }
   ]
  },
  {
   "title": "State",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Text",
     "query": "SELECT last(\"value\") FROM \"autogen\".\"Text\" WHERE (\"idx\"::tag = '9453')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idx::tag", "operator": "=", "value": "9453" }
     ]
    }
   ]
  },
  { "title": "Cycles", "type": "library-panel-ref", "gridPos": { "h": 4, "w": 2, "x": 3, "y": 4 } },
  {
   "title": "Battery SOC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Smartshunt",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Percentage",
     "query": "SELECT last(\"value\") FROM \"autogen\".\"Percentage\" WHERE (\"idx\"::tag = '9454')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idx::tag", "operator": "=", "value": "10352" }
     ]
    },
    {
     "alias": "Basen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "basengreen",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type::tag", "operator": "=", "value": "soc" }
     ]
    },
    {
     "alias": "JK",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jk",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type::tag", "operator": "=", "value": "soc" }
     ]
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Smartshunt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Voltage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idx::tag", "operator": "=", "value": "9462" }
     ]
    },
    {
     "alias": "Basen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "basengreen",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type::tag", "operator": "=", "value": "battery_voltage" }
     ]
    },
    {
     "alias": "JK",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jk",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type::tag", "operator": "=", "value": "battery_voltage" }
     ]
    }
   ]
  },
  {
   "title": "Battery Ampere",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Smartshunt",
     "measurement": "Current",
     "query": "SELECT \"value\" FROM \"Current\" WHERE (\"idx\"::tag = '9461')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "idx::tag", "operator": "=", "value": "9461" }
     ]
    },
    {
     "alias": "Basen",
     "measurement": "basengreen",
     "query": "SELECT \"value\" FROM \"basengreen\" WHERE (\"type\"::tag = 'battery_current')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type::tag", "operator": "=", "value": "battery_current" }
     ]
    },
    {
     "alias": "JK",
     "measurement": "jk",
     "query": "SELECT \"value\" FROM \"Current\" WHERE (\"idx\"::tag = '9461')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type::tag", "operator": "=", "value": "battery_current" }
     ]
    }
   ]
  },
  {
   "title": "Battery Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Basen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "idx::tag", "operator": "=", "value": "9466" }
     ]
    },
    {
     "alias": "JK",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jk",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type::tag", "operator": "=", "value": "battery_kw" }
     ]
    }
   ]
  },
  { "title": "Cell Min/Max/Avg/Diff", "type": "library-panel-ref", "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 } },
  {
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "$tag_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id::tag" ], "type": "tag" }
     ],
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type::tag", "operator": "=", "value": "alarm" }
     ]
    }
   ]
  },
  { "title": "Battery SOC/Voltage", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 } },
  {
   "title": "Battery Volt/Ampere",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Volt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type::tag", "operator": "=", "value": "battery_voltage" }
     ]
    },
    {
     "alias": "Ampere",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type::tag", "operator": "=", "value": "battery_current" }
     ]
    }
   ]
  },
  {
   "title": "JK Cell Voltage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Cell 2",
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cell::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Cell 2",
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cell::tag", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Cell 3",
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cell::tag", "operator": "=", "value": "3" }
     ]
    },
    {
     "alias": "Cell 4",
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cell::tag", "operator": "=", "value": "4" }
     ]
    },
    {
     "alias": "Cell 5",
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cell::tag", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "Cell 6",
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cell::tag", "operator": "=", "value": "6" }
     ]
    },
    {
     "alias": "Cell 7",
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cell::tag", "operator": "=", "value": "7" }
     ]
    },
    {
     "alias": "Cell 8",
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cell::tag", "operator": "=", "value": "8" }
     ]
    },
    {
     "alias": "Cell 9",
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cell::tag", "operator": "=", "value": "9" }
     ]
    },
    {
     "alias": "Cell 10",
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cell::tag", "operator": "=", "value": "10" }
     ]
    },
    {
     "alias": "Cell 11",
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cell::tag", "operator": "=", "value": "11" }
     ]
    },
    {
     "alias": "Cell 12",
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cell::tag", "operator": "=", "value": "12" }
     ]
    },
    {
     "alias": "Cell 13",
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cell::tag", "operator": "=", "value": "13" }
     ]
    },
    {
     "alias": "Cell 14",
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cell::tag", "operator": "=", "value": "14" }
     ]
    },
    {
     "alias": "Cell 15",
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cell::tag", "operator": "=", "value": "15" }
     ]
    },
    {
     "alias": "Cell 16",
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cell::tag", "operator": "=", "value": "16" }
     ]
    }
   ]
  },
  {
   "title": "JK Min/Max/Avg Voltage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type::tag", "operator": "=", "value": "lowest_voltage" }
     ]
    },
    {
     "alias": "Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type::tag", "operator": "=", "value": "highest_voltage" }
     ]
    },
    {
     "alias": "Avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type::tag", "operator": "=", "value": "v_avg_cell" }
     ]
    }
   ]
  },
  {
   "title": "JK Voltage Difference",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "alias": "Diff",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type::tag", "operator": "=", "value": "voltage_diff" }
     ]
    }
   ]
  },
  {
   "title": "Basen Temperature Probes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "temp::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "temp::tag", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "temp::tag", "operator": "=", "value": "3" }
     ]
    },
    {
     "alias": "4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "temp::tag", "operator": "=", "value": "4" }
     ]
    },
    {
     "alias": "5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "temp::tag", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "PT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "temp::tag", "operator": "=", "value": "powertube" }
     ]
    }
   ]
  },
  {
   "title": "Enphase Production",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"domoticz_home\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"Instant\"\r\n    and r.idx == \"8023\"\r\n  )\r\n  |> yield()\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV Panel Generation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"domoticz_home\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"Instant\"\r\n    and r.idx == \"8111\"\r\n  )\r\n  |> yield()\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "from(bucket:\"domoticz_home\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"Instant\"\r\n    and r.idx == \"8112\"\r\n  )\r\n  |> yield()\r\n"
    },
    {
     "query": "from(bucket:\"domoticz_home\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"Instant\"\r\n    and r.idx == \"8115\"\r\n  )\r\n  |> yield()\r\n"
    },
    {
     "query": "from(bucket:\"domoticz_home\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"Instant\"\r\n    and r.idx == \"8109\"\r\n  )\r\n  |> yield()\r\n"
    },
    {
     "query": "from(bucket:\"domoticz_home\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"Instant\"\r\n    and r.idx == \"8114\"\r\n  )\r\n  |> yield()\r\n"
    },
    {
     "query": "from(bucket:\"domoticz_home\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"Instant\"\r\n    and r.idx == \"8113\"\r\n  )\r\n  |> yield()\r\n"
    },
    {
     "query": "from(bucket:\"domoticz_home\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"Instant\"\r\n    and r.idx == \"8110\"\r\n  )\r\n  |> yield()\r\n"
    },
    {
     "query": "from(bucket:\"domoticz_home\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"Instant\"\r\n    and r.idx == \"8108\"\r\n  )\r\n  |> yield()\r\n"
    },
    {
     "query": "from(bucket:\"domoticz_home\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"Instant\"\r\n    and r.idx == \"8105\"\r\n  )\r\n  |> yield()\r\n"
    },
    {
     "query": "from(bucket:\"domoticz_home\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"Instant\"\r\n    and r.idx == \"8103\"\r\n  )\r\n  |> yield()\r\n"
    },
    {
     "query": "from(bucket:\"domoticz_home\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"Instant\"\r\n    and r.idx == \"8104\"\r\n  )\r\n  |> yield()\r\n"
    },
    {
     "query": "from(bucket:\"domoticz_home\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"Instant\"\r\n    and r.idx == \"8107\"\r\n  )\r\n  |> yield()\r\n"
    },
    {
     "query": "from(bucket:\"domoticz_home\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"Instant\"\r\n    and r.idx == \"8106\"\r\n  )\r\n  |> yield()\r\n"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "Watt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"domoticz_home\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"P1Actual\"\r\n    and r.idx == \"1768\"\r\n  )\r\n  |> aggregateWindow(every: $__interval, fn: mean)\r\n  |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Usage Today (Watt)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"domoticz_home\")\r\n  |> range(start: today())\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"Usage-current\"\r\n    and r.idx == \"1768\"\r\n  )\r\n  |> aggregateWindow(every: 1h, fn: count)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "from(bucket:\"domoticz_home\")\r\n  |> range(start: today())\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"Delivery-current\"\r\n    and r.idx == \"1768\"\r\n  )\r\n  |> aggregateWindow(every: 1h, fn: count)"
    }
   ]
  },
  {
   "title": "Battery Ampere",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "Basen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "basengreen",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type::tag", "operator": "=", "value": "balance_current" }
     ]
    },
    {
     "alias": "JK",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "jk",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type::tag", "operator": "=", "value": "battery_current" }
     ]
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Smartshunt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Voltage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idx::tag", "operator": "=", "value": "9462" }
     ]
    },
    {
     "alias": "Basen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "basengreen",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type::tag", "operator": "=", "value": "battery_voltage" }
     ]
    },
    {
     "alias": "JK",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jk",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type::tag", "operator": "=", "value": "battery_voltage" }
     ]
    }
   ]
  },
  {
   "title": "Battery SOC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Smartshunt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Percentage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idx::tag", "operator": "=", "value": "10352" }
     ]
    },
    {
     "alias": "Basen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "basengreen",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type::tag", "operator": "=", "value": "soc" }
     ]
    },
    {
     "alias": "JK",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "jk",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type::tag", "operator": "=", "value": "soc" }
     ]
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "Watt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$wbattery$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type::tag", "operator": "=", "value": "battery_power" }
     ]
    }
   ]
  }
 ]
}